export const environment = {
  production: true,
  global_logo: undefined,
  primaryColor: '#DC143C',
  url_prefix: 'url_backend/',
  url_dashboard: 'url_dashboard/',
  url_frontend: 'urlFrontend/',
  nom: 'nomInstance',
  countrycode: 'code_country',
  avaible_language: ['fr', 'en', 'es'],
  default_language: 'langue',
  firebase: {
    apiKey: 'apikey',
    authDomain: 'authdomain',
    projectId: 'projectid',
    storageBucket: 'storagebucket',
    messagingSenderId: 'messagingsenderid',
    appId: 'appid',
    measurementId: 'measurementid',
  },
};
